CREATE TABLE autores (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) UNIQUE,
    birth_year INTEGER,
    death_year INTEGER
);

CREATE INDEX idx_author_name ON autores (name);

CREATE TABLE libros (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(255) NOT NULL,
    author_id      BIGINT       NOT NULL REFERENCES autores (id),
    language       VARCHAR(255) NOT NULL,
    download_count INTEGER      NOT NULL
);
