CREATE TABLE socios (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL UNIQUE,
    document_id   VARCHAR(255) NOT NULL UNIQUE,
    status        VARCHAR(20)  NOT NULL,
    registered_at DATE         NOT NULL
);

CREATE TABLE ejemplares (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id        BIGINT       NOT NULL REFERENCES libros (id),
    inventory_code VARCHAR(255) NOT NULL UNIQUE,
    status         VARCHAR(20)  NOT NULL
);

CREATE INDEX idx_copy_book ON ejemplares (book_id);

CREATE TABLE prestamos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    copy_id     BIGINT      NOT NULL REFERENCES ejemplares (id),
    member_id   BIGINT      NOT NULL REFERENCES socios (id),
    loan_date   DATE        NOT NULL,
    due_date    DATE        NOT NULL,
    return_date DATE,
    status      VARCHAR(20) NOT NULL
);

CREATE INDEX idx_loan_member ON prestamos (member_id);
CREATE INDEX idx_loan_status ON prestamos (status);
