-- Vincula un usuario CLIENTE con su socio.
ALTER TABLE usuarios
    ADD COLUMN member_id BIGINT UNIQUE REFERENCES socios (id);

-- Reservas: un socio solicita un título; el bibliotecario la cumple prestando un ejemplar.
CREATE TABLE reservas (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id        BIGINT      NOT NULL REFERENCES socios (id),
    book_id          BIGINT      NOT NULL REFERENCES libros (id),
    reservation_date DATE        NOT NULL,
    status           VARCHAR(20) NOT NULL
);

CREATE INDEX idx_reserva_member ON reservas (member_id);
CREATE INDEX idx_reserva_status ON reservas (status);
