-- Contador de renovaciones por préstamo.
ALTER TABLE prestamos
    ADD COLUMN renewals INTEGER NOT NULL DEFAULT 0;

-- Multas por devolución fuera de plazo.
CREATE TABLE multas (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id  BIGINT         NOT NULL REFERENCES socios (id),
    loan_id    BIGINT         NOT NULL REFERENCES prestamos (id),
    amount     NUMERIC(10, 2) NOT NULL,
    days_late  INTEGER        NOT NULL,
    created_at DATE           NOT NULL,
    paid       BOOLEAN        NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_multa_member ON multas (member_id);
CREATE INDEX idx_multa_paid ON multas (paid);
